In [1]:
import pandas as pd
import numpy as np

C:\Users\Jared\AppData\Roaming\Python\Python37\site-packages\pandas\compat\_optional.py:138: UserWarning: Pandas requires version '2.7.0' or newer of 'numexpr' (version '2.6.8' currently installed).
  warnings.warn(msg, UserWarning)

In [5]:
data = pd.read_csv('Stock_Trading_Data.csv')

In [25]:
print(f'DataFrame shape: {data.shape}')
print(f'Num of senators: {data["senator"].unique().size}')
print(f'Num of securities: {data["ticker"].unique().size}')
print('\n')
print(data.dtypes)
data.head()

DataFrame shape: (8265, 16)
Num of senators: 54
Num of securities: 1023


senator                    object
party                     float64
sex                         int64
trade_date                 object
owner                      object
ticker                     object
type                       object
trade_amount_max          float64
trade_amount_min          float64
buy_one_year_change       float64
one_mo_vtsax_change       float64
one_year_vtsax_change     float64
buy_compare_one_year      float64
one_month_sell            float64
one_month_sell_compare    float64
weight                    float64
dtype: object

,senator,party,sex,trade_date,owner,ticker,type,trade_amount_max,trade_amount_min,buy_one_year_change,one_mo_vtsax_change,one_year_vtsax_change,buy_compare_one_year,one_month_sell,one_month_sell_compare,weight
0,Thomas Carper,1.0,1,29jan2021,Spouse,XCAPX,Purchase,50000.0,15000.0,NaN,0.031875,NaN,NaN,NaN,NaN,4.06
1,Patrick Toomey,0.0,1,28jan2021,Child,GME,Sale,15000.0,1000.0,NaN,0.016324,NaN,NaN,-0.438378,-0.454702,1.00
2,Jerry Moran,0.0,1,27jan2021,Spouse,COST,Sale,15000.0,1000.0,NaN,0.054616,NaN,NaN,-0.044025,-0.098641,1.00
3,Jerry Moran,0.0,1,27jan2021,Self,COST,Sale,15000.0,1000.0,NaN,0.054616,NaN,NaN,-0.044025,-0.098641,1.00
4,Patrick Toomey,0.0,1,27jan2021,Child,SHOP,Sale,15000.0,1000.0,NaN,0.054616,NaN,NaN,0.191442,0.136826,1.00

In [18]:
unique_series = [] # table type 1
unique_lists = [] # table type 2
for col in data.columns:
    unique = data[col].unique()
    if unique.size < 20:
        unique_lists.append((col, list(unique)))
        unique_series.append(pd.Series(name = col, data = unique))
uniques = pd.concat(unique_series, axis = 1)
unique_lists

[('party', [1.0, 0.0, nan]),
 ('sex', [1, 0]),
 ('owner', ['Spouse', 'Child', 'Self', 'Joint', nan]),
 ('type', ['Purchase', 'Sale', nan]),
 ('trade_amount_max',
  [50000.0,
   15000.0,
   100000.0,
   250000.0,
   1000000.0,
   5000000.0,
   nan,
   500000.0,
   25000000.0,
   50000000.0]),
 ('trade_amount_min',
  [15000.0,
   1000.0,
   50000.0,
   100000.0,
   500000.0,
   1000000.0,
   nan,
   250000.0,
   5000000.0,
   25000000.0]),
 ('weight', [4.0599999, 1.0, 9.3800001, 21.879999, 31.25, nan])]

In [42]:
senators = data.pivot_table(index = 'ticker', columns = 'senator', values = 'trade_amount_max', aggfunc = 'sum')